
LIT_DEFAULT_ARGS ?=

# Set default number of threads to use
ifdef THREADS
DEFAULT_THREADS = $(THREADS)
LIT_DEFAULT_ARGS += --threads=$(THREADS)
else
DEFAULT_THREADS = 2
endif

ifdef VERBOSE
	BATCH_VERBOSE := 1
	LIT_DEFAULT_ARGS += -v --show-unsupported --show-xfail
else
	CMD_VERB ?= @
	NOPRINTD ?= --no-print-directory
	LIT_DEFAULT_ARGS += -sv --show-unsupported --show-xfail
endif



INTERNAL_CMAKE_OPTIONS :=

# Configure the build type
ifdef BUILD
	INTERNAL_CMAKE_OPTIONS += -DCMAKE_BUILD_TYPE=$(BUILD)
endif

# Configure install prefix
ifdef PREFIX
	INTERNAL_CMAKE_OPTIONS += -DCMAKE_INSTALL_PREFIX=$(PREFIX)
endif

# Configuration for c++1y
ifdef CXX1Y
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_CXX1Y=$(CXX1Y)
endif

# Configure warnings used during build
ifdef ALL_WARNINGS
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_ALL_WARNINGS=$(ALL_WARNINGS)
endif
